### ISSUE TITLE
setNodes from useReactFlow crashes as parent node cannot be found

### ISSUE THREAD

**Issue by peilingjiang** [xyflow/xyflow#4455] opened 2024-07-16 04:48 UTC
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.2
- Browser and version: Chrome (latest)
- OS and version: MacOS (latest)

### Describe the Bug

When using the `setNodes` function derived from `useReactFlow`, it always crashes when there's a parent node with children, while I make sure that I have sorted the array and the parent nodes are handled first. Actually, if I just replace the function with the one derived from useNodesState (i.e. `const [nodes, setNodes, onNodesChange] = useNodesState([])`), it works. So I think there are something wrong with the instance produced by `useReactFlow`.

### Steps to reproduce the bug or issue

See above.

### Expected behavior

See above.

**Comment by moklick** [comment] 2024-07-16 13:33
How can I reproduce this?

**Comment by MaxiCB** [comment] 2024-08-12 05:57
I am currently facing the same issue using `next@14.2.5` with `reactflow@^12.0.2`. I have a `placeholder` node that when clicked will add a new node to the flow as a child of another node. When attempting to use `const {setNodes} = useReactFlow()` I receive `Parent node <id> not found`. However if I pass `setNodes` from `useNodesState` I do not encounter this error. 

I have been able to work around this issue until now. I am saving flow data in a database to allow for retrieval later, and the fix will no longer work as I lose reference to the `setNodes` function I am passing when creating the nodes initially. 

The commit 02e5515 has made it to where a error is no longer thrown, but there still seems to be underlying issues.

There is an issue where, for a lack of better terms, the child node is 'detached' from the parent is the best way I can describe it. When moving the parent node the child nodes no longer follows as expected, and an error message is continually logged to the console. 

The child nodes do not stack as expected, this can be seen in the provided examples below. In the workaround each subsequent child node is stacked on top of the parent, in the example with the issue present there does not seem to be a consistent pattern.


The following is a stripped down version of the code that replicates this issue, and how I have been able to work around it until now. Any feedback on how to resolve this issue, or fixes to address this issue are much appreciated. Please let me know if there is any additional information I can provide to further assist.

[Issue Present](https://codesandbox.io/p/sandbox/reactflow-4455-workaround-forked-5n8clq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzqk2i9l0006356f32xam7u4%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzqk2i9l0002356f7mnkxjdp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzqk2i9l0003356fkdc34p9a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzqk2i9l0005356frwd5uh32%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzqk2i9l0002356f7mnkxjdp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqk2i9l0001356fnwt9sv31%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzqk32uy0035356fp3hdjy9l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzqk2i9l0002356f7mnkxjdp%2522%252C%2522activeTabId%2522%253A%2522clzqk32uy0035356fp3hdjy9l%2522%257D%252C%2522clzqk2i9l0005356frwd5uh32%2522%253A%257B%2522id%2522%253A%2522clzqk2i9l0005356frwd5uh32%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqk2i9l0004356fqkbff5mr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clzqk2i9l0004356fqkbff5mr%2522%257D%252C%2522clzqk2i9l0003356fkdc34p9a%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzqk2i9l0003356fkdc34p9a%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) 

[Workaround - No longer working in my use case for reasons described above](https://codesandbox.io/p/sandbox/intelligent-hypatia-cyjp2x?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzqk2i9l0006356f32xam7u4%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzqk2i9l0002356f7mnkxjdp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzqk2i9l0003356fkdc34p9a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzqk2i9l0005356frwd5uh32%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzqk2i9l0002356f7mnkxjdp%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqk2i9l0001356fnwt9sv31%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzqk32uy0035356fp3hdjy9l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzqk2i9l0002356f7mnkxjdp%2522%252C%2522activeTabId%2522%253A%2522clzqk32uy0035356fp3hdjy9l%2522%257D%252C%2522clzqk2i9l0005356frwd5uh32%2522%253A%257B%2522id%2522%253A%2522clzqk2i9l0005356frwd5uh32%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzqk2i9l0004356fqkbff5mr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clzqk2i9l0004356fqkbff5mr%2522%257D%252C%2522clzqk2i9l0003356fkdc34p9a%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clzqk2i9l0003356fkdc34p9a%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by moklick** [comment] 2024-08-27 15:56
This is weird. It seems that the order of the nodes gets messed up somehow. We have to check it.

**Comment by moklick** [comment] 2024-08-28 14:36
This is fixed in 12.2.0

**Closed by moklick** 2024-08-28 14:36 UTC
Labels: bug, topic:subflows
