### ISSUE TITLE
Lagging when dragging nodes

### ISSUE THREAD

**Issue by MatheusRoichman** [xyflow/xyflow#3922] opened 2024-02-17 03:02 UTC
### Describe the Bug

I noticed that React Flow has a little delay while dragging a node. 
Like, when I drag a node, the cursor goes first to the desired position, and after a little time the node goes to the desired position.
This behavior can be seen even on the official examples. It is more visible on flows with snapToGrid set to true, but also happens on normal flows.

### Your Example Website or App

https://reactflow.dev/examples/nodes/custom-node

### Steps to Reproduce the Bug or Issue

Just try to drag a node and you'll notice.

### Expected behavior

As a user, I expect the node dragging to be kind of more instantly, less delayed.

### Platform

- OS: Windows 11
- Browser: Chrome, Brave
- Version:  Chrome 109.0.5414.120 (64 bits), Brave 1.62.165 (64 bits)

**Comment by peterkogo** [comment] 2024-02-19 09:35
I think you are seeing the desired behavior of snapToGrid. It does not move the node freely with your mouse but only when you hit the next grid point

**Comment by MatheusRoichman** [comment] 2024-02-19 18:33
> I think you are seeing the desired behavior of snapToGrid. It does not move the node freely with your mouse but only when you hit the next grid point

It is more perceptible on the snapToGrid, but you can also see a bit of this on a flow with snapToGrid={false}.

**Comment by peterkogo** [comment] 2024-02-20 09:27
What hardware are you running on? Can you create a video of this behavior? 
I really can't reproduce this on a 120Hz monitor.

**Comment by MatheusRoichman** [comment] 2024-02-21 16:16
I use a 60Hz monitor.

On Canva, this delay doesn't happen. The application I'm building with React Flow should be similar to it. But it have this delay, which is not happening on Canva using the same monitor, so I don't think this is the problem.

Please see attached a video of a comparison between the two behaviors:

https://github.com/xyflow/xyflow/assets/75812510/f100a61b-9763-4bff-9f03-8f2375b02d3f

**Comment by peterkogo** [comment] 2024-02-22 09:51
In your video there seems to be a single frame difference in latency compared to canva. You might want to check your performance tab to further investigate what might be causing the additional frame of delay on your side. I can't even reproduce this behavior with 6x CPU throttling and 120Hz (8.33 ms per frame) refresh rate on my device.

This might be expected behavior. React Flow has to check/compute a fair number of constraints when moving a node, that I assume canva does not. I will close this issue for now. Feel free to reopen it, if you have found more specific details regarding this issue. 

https://github.com/xyflow/xyflow/assets/7165378/7d127486-5aa0-4bdc-8a95-5d15ba4bbbc3

**Closed by peterkogo** 2024-02-22 09:51 UTC
