### ISSUE TITLE
Children positionAbsolute won't update when using subflows 

### ISSUE THREAD

**Issue by ariannargesi** [xyflow/xyflow#2603] opened 2022-11-27 09:00 UTC
### Describe the Bug

I'm using Subflows in my app. when I move a group around, I can see the new absolute position for the group itself, but no new value for its children in the onNodeChange event handler. Updated positions are available in ReactFlow's internal state. But they would available in the onNodeChange handler 

### Your Example Website or App

https://codesandbox.io/s/nameless-dawn-k3784e?file=/App.js

### Steps to Reproduce the Bug or Issue

 Open [codesandbox](https://codesandbox.io/s/nameless-dawn-k3784e?file=/App.js)
 Move "Group A" around 
 Check the console  

### Expected behavior

Ideally, the onNodeChange handler should give us the information about all nodes that changed with dragging, But right now only gives us the data about dragged node itself

### Platform

- OS: [Ubuntu]
- Browser: [chromium]

**Comment by septum** [comment] 2023-05-31 17:38
Is this the expected behaviour?

**Comment by ariannargesi** [comment] 2023-06-01 10:05
> Is this the expected behaviour?

No, It is not. But if you need the updated position, you can directly read that data with useStore api. nodeInternals is what you need.
https://reactflow.dev/docs/api/hooks/use-store/

**Comment by moklick** [comment] 2024-05-06 18:25
This will be fixed in v12, where `positionAbsolute` is no longer part of the user node but only available for internal nodes.

**Comment by moklick** [comment] 2024-07-09 15:16
Since React Flow 12 we distinguish between user nodes and internal nodes and do not expose position absolute for user nodes anymore. If you want to get an internal node you could get it by using the `getInternalNode` helper.

**Closed by moklick** 2024-07-09 15:16 UTC
Labels: v12
