### ISSUE TITLE
Error when clicking edge source end with onReconnect

### ISSUE THREAD

**Issue by tylercallahan** [xyflow/xyflow#4459] opened 2024-07-16 22:15 UTC
### What platform were you using when you found the bug?

- React Flow version: 12.0.0
- Browser and version: Chrome 126.0.6478.127
- OS and version: macOS 13.0

### Live code example

https://codesandbox.io/p/sandbox/frosty-paper-p4r4gp

### Describe the Bug

When an edge is connected between two handles of type `'source'`, and the `onReconnect` prop has been passed to the `ReactFlow` component (following the [Reconnect Edge example](https://reactflow.dev/examples/edges/reconnect-edge)), attempting to reconnect the "source" end of the edge raises an error (and causes the edge to disappear).

```
TypeError: Cannot read properties of null (reading 'position')
  at Object.onPointerDown
  at handleEdgeUpdater
  at onReconnectSourceMouseDown
```

It appears the error is happening [here](https://github.com/xyflow/xyflow/blob/f032638de3874cfc66291c98ccb6d822114491d4/packages/system/src/xyhandle/XYHandle.ts#L93), as `fromHandleInternal` is `null` in this scenario.

Note that this error did not happen in React Flow 11.11.1, but appeared when we upgraded to React Flow 12.0.0. Similar to the sandbox provided, our application is using type `'source'` for handles, although each handle can act as a source or target (is connectable in either direction), and uses a custom node and edge. When I change the target handle to type `'target'`, this error no longer occurs (and the edge can be reconnected from either end).

### Steps to reproduce the bug or issue

1. Click the right side (source) of the top edge connecting the "Bi Directional 2" node to "Bi Directional 1".
2. Observe error, and edge disappears.

Note that this example sandbox was generated from the [Custom Edges example](https://reactflow.dev/examples/edges/custom-edges), and the only change made was adding the `onReconnect` callback and passing it to the `ReactFlow` component.

### Expected behavior

As a user, I expected to be able to reconnect the source end of the edge, but instead the edge disappeared when clicking the source end and an error was raised in the console.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/e7392605-faf6-4d82-8f6c-89f0f845e091)

**Comment by moklick** [comment] 2024-07-17 14:36
Thanks we will check it! It looks like a bug.

**Comment by moklick** [comment] 2024-07-18 14:22
This is fixed in 12.0.3

**Closed by moklick** 2024-07-18 14:22 UTC
Labels: bug

**Comment by Derick1530** [comment] 2024-08-22 09:03
I'm experiencing the following error when using custom handles (v12.0.3):


```
TypeError: Cannot read properties of null (reading 'position')
  at Object.onPointerDown
  at handleEdgeUpdater
  at onReconnectSourceMouseDown
```

### Details:
In my project, I have custom handles that are dynamically added via a side panel. The error seems to be triggered under specific conditions related to the width of the custom node:

When I set the width of the parent custom handle to 100% and then dynamically change the node width, the error consistently occurs.
However, if I don't specify the width at all, the error disappears.
It seems the issue is tied to how the width is managed for these custom handles when the node width is updated.

### Steps to Reproduce:
- Set the parent custom handle width to 100%.
- Dynamically update the content of your node to cause a change in the width of the custom node through a side panel.
Add an additional handle.
- Interact with the handles and observe the behavior (in v12.0.3, you won't get an error, but the handles won’t function as expected).
### Screenshot:
<img width="579" alt="image" src="https://github.com/user-attachments/assets/bf0f39f7-e41b-444a-bc30-8d7e705702e7">

**Comment by peanudge** [comment] 2024-09-02 08:04
i had similar experiences(like above case shared by @Derick1530) after i update node's data that raise changes of handle state. but, i resolved by calling `updateNodeInternals(node.id)` at next render cycle after changing data related handles.

**Comment by Derick1530** [comment] 2024-09-02 15:55
just saw this in the docs : https://reactflow.dev/api-reference/components/handle#dynamic-handles
