### ISSUE TITLE
Unexpected connection behaviour when using a updateNodeInternals

### ISSUE THREAD

**Issue by Ivan239** [xyflow/xyflow#4027] opened 2024-03-15 18:06 UTC
### Describe the Bug

I want to change height of node when starting connection. But it becomes invisible and node is not updating. How to fix it?

### Your Example Website or App

https://codesandbox.io/p/sandbox/mystifying-meadow-lc6kfs?file=%2Fstyle.css&utm_medium=sandpack

### Steps to Reproduce the Bug or Issue

Start connecting
Current connection becomes invisible

### Expected behavior

Current connection visible and handle moves to the center (and doesn't stay in old center)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by moklick** [comment] 2024-03-16 11:12
Can you check your codesandbox? It seems to be the easy connect example.

**Comment by Ivan239** [comment] 2024-03-17 16:28
> Can you check your codesandbox? It seems to be the easy connect example.

yep, sorry, copy wrong link https://codesandbox.io/p/sandbox/blissful-wilson-3zx9f7?file=%2Fstyle.css%3A12%2C16

**Comment by peterkogo** [comment] 2024-08-06 09:21
This is indeed not intended behavior. This uncovered a potential improvement we should implement. You can track it over at #4520.

For now, I suggest you use `nodeOrigin={[0.5, 0.5]}` in your flow which leaves any centered handles in the same position and extends all nodes from a centered origin (which is what you'd want to do anyway I suppose).

**Comment by peterkogo** [comment] 2024-08-14 09:04
This will be fixed by #4548

**Closed** 2024-08-14 14:39 UTC
Labels: bug, react, svelte
