### ISSUE TITLE
Calling reactFlow.updateEdgeData or reactFlow.updateNodeData in multiple places at the same time freezes the graph

### ISSUE THREAD

**Issue by tubarao312** [xyflow/xyflow#4779] opened 2024-11-03 20:55 UTC
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: Latest
- Browser and version: Chrome, Latest
- OS and version: Windows 11, Latest

### Describe the Bug

I have a project where I'm making multiple API calls that can arrive at different times, and I'm trying to update node & edge data as they arrive. 

Whenever I start making a lot of API calls and two happen to arrive at the same time, I update edge and node data simultaneously. I'm yet to figure out how to trigger it every time, but in my app, the more requests the user makes, the more likely it is that the bug triggers.

From the moment it happens, the graph can no longer be updated with new edges or nodes, or edge or node updates, it essentially turns into "read-only mode".

### Steps to reproduce the bug or issue

1. Simulate a lot of async calls using setTimeout
2. When those calls finish, call useReactFlow().updateNodeData or updateEdgeData
3. Nodes/Edges stop being updated, added, or removed!

### Expected behavior

I would expect the graph to be able to accept multiple modifications at the same time and properly figure out how to deal with them (merging updates), or at least be able to accept updates across different nodes and edges. Instead, the state becomes locked completely whenever the bug happens.

### Additional context

- I disabled all updateEdgeData calls, and the bug started appearing only for nodes (so nodes couldn't be added or updated, but edges were fine)
- I disabled all updateNodeData calls, and the bug disappeared from nodes completely!
- This happens for updates across different nodes and edges, not just updating the same edge/node.
- I've only recently updated my app to use updateNode/EdgeData. Previously, I would use React's `useContext` hook to pass setters/updaters around, and that worked fine with lots of requests arriving at the same time.
- All graph updates/modifications stop working, not just updateNodeData or updateEdgeData.

**Comment by Aki-7** [comment] 2024-11-05 14:39
Hi, all!

I probably encountered the same issue, and since I was in a bit of a rush, I forked it and made my own fixes. But I’d be glad if this gets fixed and merged into the main branch, so let me share some findings from my investigation.

Based on my initial research, it seems that part of the internal [useQueue](https://github.com/xyflow/xyflow/blob/49e74dc88241c520f4744ba9ed34bb11dc31fc48/packages/react/src/components/BatchProvider/useQueue.ts#L14) function isn’t behaving as expected. Specifically, the `shouldFlush` state is set to `false` at the end of `useIsomorphicLayoutEffect`, but it doesn’t seem to take effect as intended in some conditions.

The reason graph updates are freezing seems to be that `useIsomorphicLayoutEffect` in `useQueue` completes with `shouldFlush` still set to `true`. So, when `setShouldFlush(true)` is triggered by functions like `updateNodeData`, the `shouldFlush` state remains `true`, preventing `useIsomorphicLayoutEffect` from firing again.

Although the code doesn’t appear to be structured to cause this, here’s a possible explanation: At the end of `useIsomorphicLayoutEffect`, `setShouldFlush` should set `shouldFlush` to `false`, but then `updateNodeData` or similar functions quickly reset `shouldFlush` to `true`. Due to automatic batching in React (though I’m not entirely certain on this point), `shouldFlush` remains `true` without any change in the dependencies of `useIsomorphicLayoutEffect`, meaning it doesn’t re-trigger with `shouldFlush` as `true`.

As a result, subsequent calls to `updateNodeData` or similar functions don’t change `shouldFlush` from `true`, stopping `useIsomorphicLayoutEffect` from running again and preventing `shouldFlush` from ever resetting to `false`.

In my project, I’ve modified it as shown below, and so far, it’s been working without any issues:
https://github.com/xyflow/xyflow/compare/main...Aki-7:xyflow:celbo

I understand your [“cathedral” style of development](https://github.com/xyflow/xyflow/blob/main/CONTRIBUTING.md), but if the direction of the fix aligns, I’d be happy to contribute this as a Pull Request.

Thanks again for all your hard work on such a fantastic project!

**Comment by peterkogo** [comment] 2024-11-08 09:19
@Aki-7 Thank you so much!! This is indeed the right fix. This solves quite a number of issues connected to updating the nodes and node data.

Only nitpick: usage of BigInt is not neccessary in this case because even if you reach the end of a regular integer (`9007199254740991`), the number wraps around again which should pose no problem.

If you are quick you can open a pull request. However, because this is quite an important fix and I would like to release it asap, so I might incorporate these changes later today. I will give you a shoutout in our changelog nonetheless!

**Comment by Aki-7** [comment] 2024-11-08 09:36
Thank you!

I thought so at first too, but apparently Number.MAX_SAFE_INTEGER + 1 === Number.MAX_SAFE_INTEGER + 2.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

However, since 9,007,199,254,740,991 is a sufficiently large number, I'll go ahead and submit a pull request soon according to your suggestion! If there are any issues, please point them out during the review!

**Comment by peterkogo** [comment] 2024-11-08 09:45
@Aki-7 Oh you are absolutely right. I thought integers wrap around in javascript.

**Comment by peterkogo** [comment] 2024-11-08 09:47
Feel free to use `BigInt` in that case. We don't need to access the number anywhere else so it's completely safe.

**Closed** 2024-11-08 10:26 UTC
Labels: topic:computing

**Comment by peterkogo** [comment] 2024-11-11 12:00
This is fixed in the newest version.
