### ISSUE TITLE
Is there any Feature like when two edges are intersect each other then intersection point should be shown as broken lines or semicircles in version 11

### ISSUE THREAD

**Issue by sudarsanarao995** [xyflow/xyflow#3880] opened 2024-02-07 11:22 UTC
### Please describe the feature that you want to propose

that intersection point is not looking good in flow , so is it possible that intersection point should be shown as broken lines or semicircles ?
![image](https://github.com/xyflow/xyflow/assets/147405464/c26518a3-bb41-47e2-a2c5-071b367db80e)

**Comment by moklick** [comment] 2024-02-07 11:55
not a built-in feature and not planned - duplicate of #3859

**Closed by moklick** 2024-02-07 11:55 UTC
Labels: feature request

**Comment by sudarsanarao995** [comment] 2024-02-07 12:23
@moklick  Is there any Planned to built this feature in version 12 ?

**Comment by moklick** [comment] 2024-02-07 21:16
no, this is not planned.
