### ISSUE TITLE
useOnViewportChange doesn't call onEnd when zoom level changes using Controls

### ISSUE THREAD

**Issue by goliney** [xyflow/xyflow#4071] opened 2024-03-26 02:06 UTC
### Describe the Bug

When I change the zoom level using `Controls`, `onEnd` of `useOnViewportChange` is not called.

```
  useOnViewportChange({
    onEnd: (viewport) => console.log("end", viewport),
  });
```

### Your Example Website or App

https://codesandbox.io/p/sandbox/vigilant-payne-yxmc5n?file=%2FSidebar.js

### Steps to Reproduce the Bug or Issue

1. Open codesandbox with `useOnViewportChange` usage
2. Open console to see logs
3. Pan canvas, change zooming using mouse scroll. You'll see logs.
4. Use `+` or `-` from `<Controls />`. There'll be no logs as `onEnd` is not called.

### Expected behavior

4. `onEnd` from `useOnViewportChange` gets called when using `<Controls />`

### Screenshots or Videos

https://github.com/xyflow/xyflow/assets/2017344/ae42a435-678b-4f30-9a30-dae70ebf03ad

### Platform

- OS: macOS
- Browser: Chrome
- Version: 121.0.6167.184 (Official Build) (x86_64)

**Comment by moklick** [comment] 2024-03-28 11:31
This is the expected behaviour in v11. In v12, this changes and everything that updates the viewport (if it's the initial fitView or the controls) triggers onMove/ useOnViewportChange.

**Comment by wowtah** [comment] 2024-05-03 20:16
> This is the expected behaviour in v11. In v12, this changes and everything that updates the viewport (if it's the initial fitView or the controls) triggers onMove/ useOnViewportChange.

I am experiencing the same behaviour. I'm using the useOnViewportChange -> onEnd event to store the viewport in my database after the user has changed it.  onEnd is convenient since it saves me from capturing and debouncing all the onChange events before my database write action. 

If the user is using the Controls (zoom/fit) to manipulate the viewport, the onEnd is indeed not fired. In theory, clicking the controls is sort of the 'end' of the manipulation, so I would also expect onEnd to fire in this case. 

Can this be updated for v11? Or do I need to wait for v12?

**Comment by goliney** [comment] 2024-05-03 20:22
@wowtah you don't have to wait for v12, you can already try it out. Details: https://github.com/xyflow/xyflow/discussions/3764

**Comment by moklick** [comment] 2024-07-09 14:13
Fixed in React Flow 12! If you are using 11, you can find the migration guide here: https://reactflow.dev/learn/troubleshooting/migrate-to-v12

**Closed by moklick** 2024-07-09 14:13 UTC
Labels: v12
