### ISSUE TITLE
Node selection breaks if useNodesState() is initialized with an empty array

### ISSUE THREAD

**Issue by jasonwcfan** [xyflow/xyflow#4557] opened 2024-08-15 22:06 UTC
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.0.1
- Browser and version: Chromium Engine Version 126.0.6478.183
- OS and version: MacOS Sonoma 14.5 (23F79)

### Live code example

N/A

### Describe the Bug

I load nodes from a database and then use the `setNodes` function from `useNodesState` to load them into react flow. However I noticed that selection events no longer trigger after loading the nodes, and realized that it was because I'm calling `useNodesState()` with an empty array. If initialized with an array with at least one element (e.g. `initialNodes` below) it works fine.

It's my understanding that initializing with an empty array is standard practice, so it's odd to me that this apparently breaks react flow.
```
const initialNodes = [
  {
    id: "1",
    position: { x: 0, y: 0 },
    data: { title: "Example Source Node", description: "Test Description", sourceType: "gcs" },
    type: "example1",
  },
];
const newNodes = [{id: "2", position: {x: 500, y:0}, type: "example2"}]

const [nodes, setNodes, onNodesChange] = useNodesState([]);
setNodes(data.nodes);

useOnSelectionChange({
    onChange: useCallback(
      ({ nodes, edges }) => {
        ... some logic
        }
      },
      []
    ),
  });
```

### Steps to reproduce the bug or issue

1. Initialize useNodesState() with an empty array.
2. Import and define a callback using the `useOnSelectionChange` hook.
3. Call `setNodes` with an array of objects that represent Nodes (id, type, data, position).
4. Select a node.

### Expected behavior

Node selection should still work and the useOnSelectionChange hook should trigger.

**Comment by bcakmakoglu** [comment] 2024-08-15 22:21
[Seems to work fine for me in this sandbox.](https://codesandbox.io/p/sandbox/trusting-burnell-y29h6n)

Can you provide a reproduction of the issue? 
Passing an empty array doesn't seem to be the cause of the problem since it works fine in a sandbox 🤔

**Comment by jasonwcfan** [comment] 2024-08-17 01:39
Thanks @bcakmakoglu . Might be a typing issue let me try and post back with what i find.

**Comment by peterkogo** [comment] 2024-09-19 10:37
I will close this issue for now. Feel free to reopen it with a reproduction or head over for [Discord](https://discord.gg/RVmnytFmGW) if you have any questions.

**Closed by peterkogo** 2024-09-19 10:37 UTC
Labels: needs response
