### ISSUE TITLE
How to Extend Viewport or Canvas Size When Adding a New Node from the Menu Toolbar

### ISSUE THREAD

**Issue by hrishikesh2727** [xyflow/xyflow#4817] opened 2024-11-15 13:13 UTC
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.4
- Browser and version: 130.0.6723.117
- OS and version: Windows 11

### Describe the Bug

**Use Case**: Add a Node from the Menu on the Viewport/Canvas

**Issue**:
1. When nodes/activities are added from the menu toolbar and they extend beyond the right side of the canvas, the Viewport/Canvas size does not automatically extend.
2. All controls are slightly shifted to the left.

### Steps to reproduce the bug or issue

1. Open the app.
2. Click on "Add Activity/Node" from the floating toolbar.
3. Add multiple nodes using the floating toolbar.
4. Issue: The Viewport/Canvas does not extend or shift controls when multiple activities/nodes are added.

### Expected behavior

The Viewport/Canvas should extend when multiple Activities/Nodes are added.

### Screenshots or Videos

https://github.com/user-attachments/assets/13252ac4-c620-4759-8d90-c46b088b00f2

### Additional context

When we drag Activity/Node then Viewport/Canvas will get extend but when we add activity/node using menu then its not extending.

**Comment by moklick** [comment] 2024-11-16 15:19
The issue here is that the input of the new node gets focused. By default the browser wants to make this input element visible. To fix this, you could use `.focus({ focusVisible: false })` https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#focusvisible or try to use the CSS rule `.react-flow { position: fixed }` (this only works for fullscreen apps). 

Duplicate of #4667

**Closed by moklick** 2024-11-16 15:19 UTC

**Comment by hrishikesh2727** [comment] 2024-11-18 13:03
I added `inputElement.current.focus({ preventScroll: true });` and it’s working as expected. However, when I tried using CSS `(react-flow { position: fixed; })`, it didn’t work.

FYI - I am using xy flow.

Thank you so much for your help!

https://github.com/user-attachments/assets/607c3dbe-c08f-44af-be45-30be976fdf86
