### ISSUE TITLE
Keyboard stopped working in SvelteFlow

### ISSUE THREAD

**Issue by JDR42** [xyflow/xyflow#4891] opened 2024-12-15 21:31 UTC
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: SvelteFlow
- Browser and version: Chrome & Firefox
- OS and version: Win11

### Live code example

https://stackblitz.com/edit/h9trywep?file=index.html

### Describe the Bug

Keyboard stopped working in SvelteFlow.

Ex:
* Backspace will not delete selected node
* Cannot use CTRL modifier to mutliselect

### Steps to reproduce the bug or issue

1. Go here: https://svelteflow.dev/examples/nodes/update-node
2. Select an edge and hit the `Backspace` key.  Try to multiselect with CTRL. Note all keyboard behavior is working fine here.
3. Open in StackBlitz with the link in the lower-right
4. Try step 2 here and it fails.

### Expected behavior

As a user, I expected to get keyboard functionality in the stackblitz demo as in the website demo.

**Comment by peterkogo** [comment] 2024-12-17 10:44
I can confirm this is happening. This seems to be caused by one of our dependencies.

**Comment by JDR42** [comment] 2024-12-18 07:55
@nicbaz Works great. You're amazing! Cheers

**Comment by peterkogo** [comment] 2024-12-18 10:39
This was fixed in Svelte Flow 0.1.26.

**Closed by peterkogo** 2024-12-18 10:39 UTC
Labels: bug, svelte
