### ISSUE TITLE
Node text getting blurred when another div is scrolled (svelteflow)

### ISSUE THREAD

**Issue by ChevalMonsieur** [xyflow/xyflow#4228] opened 2024-04-30 12:29 UTC
### Describe the Bug

on my svelte project, with custom nodes that have objects in them, whenever i scroll on another div that is not on the graph, my text becomes a bit blurry until i move back a node or the posision of the view of the graph.

### Steps to Reproduce the Bug or Issue

I haven't been able to reproduce the bug :( but I hope somebody have had the same thing and knows how to fix it

### Expected behavior

when I scroll, nothing gets blurry.

### Screenshots or Videos

Before scrolling : 
![image](https://github.com/xyflow/xyflow/assets/126174925/4781799d-5682-45d2-8df3-6b07453093ea)

After scrolling : 
![image](https://github.com/xyflow/xyflow/assets/126174925/4938181f-dce1-4024-8548-28f8ace26523)

### Platform

- OS: [ Linux (Ubuntu 22.04) ]
- Browser: [ None (Neutralino) ]
- Version: [ ^0.0.41 ]

### Additional context

I guess it's just a technique to save some memory or something but I didin't see anyway to deactiavte it

**Comment by peterkogo** [comment] 2024-05-06 10:15
I think this is connected to a plethora of issues concerning subpixel rendering/transforms/css transitions (#3282, #4074)
Some of these issues seem to be amplified on Linux.

The library itself does not do any optimizations that could result in blurring.

**Comment by peterkogo** [comment] 2024-08-26 15:55
This is a duplicate of #4074. We will continue discussion there.

**Closed by peterkogo** 2024-08-26 15:55 UTC
