### ISSUE TITLE
`updateNodeData` + React 17 

### ISSUE THREAD

**Issue by ludenge** [xyflow/xyflow#4680] opened 2024-09-23 09:51 UTC
### What platform were you using when you found the bug?

- React Flow / Svelte Flow version: 12.3.0
- React version: 17.0.2
- Browser and version: 128.0.6613.138
- OS and version: 14.1.2 (23B92)

### Describe the Bug

Based on official examples, Modify content NumberInput.js
https://reactflow.dev/learn/advanced-use/computing-flows#computing-data

```
 import React, { useCallback, useState, useEffect } from "react";
import { Handle, Position, useReactFlow } from "@xyflow/react";

function NumberInput({ id, data }) {
  const { updateNodeData } = useReactFlow();

  const onChange = useCallback((evt) => {
    const cappedNumber = Math.min(255, Math.max(0, evt.target.value));
    updateNodeData(id, { value: cappedNumber });
  }, []);

// ------- add start --------
const [refreshKey, setRefreshKey] = useState(String(Date.now()));

  useEffect(() => {
    setRefreshKey(String(Date.now()));
  }, []);

  useEffect(() => {
    updateNodeData(id, {
      text: refreshKey,
    });
  }, [refreshKey]);
// ------- add end --------

  return (
    <div className="number-input">
      <div>{data.label}</div>
      <input
        id={`number-${id}`}
        name="number"
        type="number"
        min="0"
        max="255"
        onChange={onChange}
        className="nodrag"
        value={data.value}
      />
      <Handle type="source" position={Position.Right} />
    </div>
  );
}

export default NumberInput;

```

NumberInput will become non-editable, updateNodeData will not execute

### Steps to reproduce the bug or issue

1. React version 17.0.2
2. add the following code block to node
```
const [refreshKey, setRefreshKey] = useState(String(Date.now()));

  useEffect(() => {
    setRefreshKey(String(Date.now()));
  }, []);

  useEffect(() => {
    updateNodeData(id, {
      text: refreshKey,
    });
  }, [refreshKey]);
```

### Expected behavior

Expected to be able to input content

### Screenshots or Videos

![img_v3_02f0_7cd5e0e5-c80f-48f6-ae74-891ca9193acg](https://github.com/user-attachments/assets/efd984a4-4253-4e3c-b7c1-251060132960)

**Comment by ludenge** [comment] 2024-09-23 09:59
Changing useIsomorphicLayoutEffect to useEffect will fix this

**Comment by bcakmakoglu** [comment] 2024-09-23 10:03
[I can't reproduce this in this sandbox.](https://codesandbox.io/p/sandbox/zealous-bohr-6mmsdx?file=%2FNumberInput.js%3A7%2C1-8%2C1)
Adding the code you suggested changes nothing about the behavior of the input, it still works fine before and after adding the code.
The key isn't even used so I'm not sure what it's even for.

**Comment by ludenge** [comment] 2024-09-23 10:09
> [I can't reproduce this in this sandbox.](https://codesandbox.io/p/sandbox/zealous-bohr-6mmsdx?file=%2FNumberInput.js%3A7%2C1-8%2C1) Adding the code you suggested changes nothing about the behavior of the input, it still works fine before and after adding the code. The key isn't even used so I'm not sure what it's even for.

You need to change the react version to 17.0.2
Modify the index file as follows
```
import React, { StrictMode } from "react";
import ReactDOM from "react-dom";
import "./styles.css";

import App from "./App";

ReactDOM.render(<App />, document.getElementById("root"));

// import React, { StrictMode } from "react";
// import { createRoot } from "react-dom/client";
// import "./styles.css";

// import App from "./App";

// const root = createRoot(document.getElementById("root"));
// root.render(
//   <StrictMode>
//     <App />
//   </StrictMode>
// );

```

**Comment by bcakmakoglu** [comment] 2024-09-23 10:19
That creates some other issues like the edges not rendering but the input still seems to work fine.

[Here's my sandbox.](https://codesandbox.io/p/sandbox/stupefied-parm-zqdds3)

**Comment by ludenge** [comment] 2024-09-23 10:51
> That creates some other issues like the edges not rendering but the input still seems to work fine.
> 
> [Here's my sandbox.](https://codesandbox.io/p/sandbox/stupefied-parm-zqdds3)

Please see my first comment, you can copy and replace NumberInput.js.
You can enter it now because you setNumber and used number to render. UpdateNodeData was not updated successfully.

**Comment by bcakmakoglu** [comment] 2024-09-23 11:05
Ah I see, my bad I missed the part where you removed the local state and started only using the data object as a value :)

**Comment by ludenge** [comment] 2024-09-23 11:12
After changing the "useIsomorphicLayoutEffect" in the source code to "useEffect", you can enter the content, but there will be an exception when entering in Chinese. I hope it will help you locate the problem, but don't fix it like this.

**Comment by moklick** [comment] 2024-09-23 12:55
As you said, it seems to be an issue with React17 (works fine with 18). We will look into this.

**Comment by peterkogo** [comment] 2024-10-09 14:32
@ludenge First, you need to add `updateNodeData` to the dependency array of `useCallback`. 

Second, it is not recommended to use the node data directly to handle input fields. See our Computing Flows guide,[ end of section "Computing Data - Step 1"](https://reactflow.dev/learn/advanced-use/computing-flows#step-1-writing-values-to-the-data-object).

Can you please double-check, if this problem exists after you have made the adjustments. 
Moreover, please provide a forked codesandbox with the issue you have described so we can investigate.

**Comment by ludenge** [comment] 2024-10-10 02:36
reproduce the code can see the following, you will find that the input cannot be change
[https://codesandbox.io/p/sandbox/objective-haze-749pl9](https://codesandbox.io/p/sandbox/objective-haze-749pl9)

The problem is not solved
First of all, it has nothing to do with useCallback
Secondly, if you don't directly use data as the UI state, you just can't see the problem. The problem still exists, and the update operation is unsuccessful


The reproduction step of the problem is very clear. One useEffect modifies useState, and state triggers another useEffect execution. Executing updateNodeData in this useEffect will trigger the bug.
```
  const [refreshKey, setRefreshKey] = useState(String(Date.now()));

  useEffect(() => {
    setRefreshKey(String(Date.now()));
  }, []);

  useEffect(() => {
    updateNodeData(id, {
      text: refreshKey,
    });
  }, [refreshKey]);
```

My temporary solution now is not to use updateNodeData in useEffect

**Comment by ludenge** [comment] 2024-10-24 06:59
Has there been any progress on this issue?

**Comment by peterkogo** [comment] 2024-10-24 15:21
I can reproduce this issue on my end. Will investigate.

**Comment by peterkogo** [comment] 2024-11-11 12:00
@ludenge This should be fixed in the newest release. Feel free to reopen the issue, if it still persists.

**Closed by peterkogo** 2024-11-11 12:00 UTC
Labels: bug, react, topic:computing
