### ISSUE TITLE
Bad performance in Svelte 5

### ISSUE THREAD

**Issue by firehudson** [xyflow/xyflow#4111] opened 2024-04-04 09:39 UTC
### Describe the Bug

In our product we're working with svelte-5, and we're seeing bad performance for svelte-flow.

- [Svelte-4 stackblitz](https://stackblitz.com/edit/wkgk24?file=src%2Fexample%2FApp.svelte,package.json)*
- [Svelte-5 stackblitz](https://stackblitz.com/edit/spvqcm?file=package.json,src%2Fmain.js,src%2Fexample%2FApp.svelte)*
  - Updated dev-deps for svelte-5
  - Replaced `new App` with `mount(...)`
  - Wrapped `<SvelteFlow />` component in App.svelte with [`<SvelteFlowProvider>`](https://svelteflow.dev/api-reference/svelte-flow-provider)

*forked from the [svelte-flow stress test](https://svelteflow.dev/examples/nodes/stress) 

### Steps to Reproduce the Bug or Issue

1. Go to [stackblitz](https://stackblitz.com/edit/spvqcm?file=package.json,src%2Fmain.js,src%2Fexample%2FApp.svelte)
2. Try to play around with the canvas and you can observe the performance lag when compared to [official example](https://stackblitz.com/edit/wkgk24?file=src%2Fexample%2FApp.svelte,package.json)

### Expected behavior

Performance should be identical.

### Platform

- [Stackblitz](https://stackblitz.com/edit/wkgk24?file=src%2Fexample%2FApp.svelte,package.json)

**Comment by peterkogo** [comment] 2024-04-09 11:30
We will focus on porting Svelte Flow to Svelte 5 soon, you can read more about our plans for the library here https://svelteflow.dev/whats-new/2024-04-05

**Comment by tsdexter** [comment] 2024-04-20 13:40
@peterkogo any chance you have an estimated timeline planned for Svelte 5 support yet - even just a rough idea - nothing we'll hold you to, of course?

**Comment by peterkogo** [comment] 2024-05-07 10:20
@tsdexter It is coming along quite nicely. Hard to tell when the first release will be ready, though. Svelte 5 makes us rethink the architecture quite a bit. We also constantly find things where the solutions is kind of 'meh' and some good night sleep and pondering is required.
Might be anything of the realm of 2-8 weeks honestly. Also it's hard to test a lot of things because SvelteKit is not even remotely ready for Svelte 5, neither are any linting tools... In the end it might also be the ecosystem delaying the release.

**Comment by tsdexter** [comment] 2024-05-07 18:25
@peterkogo amazing, thank you. Even 2-8+ weeks allows me to start to plan accordingly. Thanks for the response!

**Comment by jycouet** [comment] 2024-08-21 14:09
Hello there, 
Any idea of when you will have a `next` version on svelte 5 ? :)

**Comment by peterkogo** [comment] 2024-08-21 14:28
@jycouet This depends on when the Svelte Team is ready to stop making big, breaking changes to their Release Candidate 😅 
We know from our side how we want to port the library and have a prototype working, but there are still too many fundamental adjustments happening, and it's too time-consuming to maintain two Svelte libraries at the same time.

**Comment by peterkogo** [comment] 2024-08-21 14:29
> @tsdexter Might be anything of the realm of 2-8 weeks honestly

I was very wrong. I think Svelte 5 is still in alpha.

**Comment by jycouet** [comment] 2024-08-21 14:31
> @jycouet This depends on when the Svelte Team is ready to stop making big, breaking changes to their Release Candidate 😅 We know from our side how we want to port the library and have a prototype working, but there are still too many fundamental adjustments happening, and it's too time-consuming to maintain two Svelte libraries at the same time.

I'm 100% with you, thank you for sharing 👍

**Comment by mcmxcdev** [comment] 2024-08-21 17:34
You can follow along the progress for Svelte 5 in https://github.com/sveltejs/svelte/milestone/9, which might or might not be an accurate representation of work left there.

> I was very wrong. I think Svelte 5 is still in alpha.

Alpha is probably too pessimistic (although I understand the sentiment based on the amount of breaking changes that the Svelte team is still landing)

**Comment by adminy** [comment] 2024-08-31 14:08
I don't think there will be major breaking changes, I've been using it in prod for a while and the only things they did are oriented around fixing what was broken and performance improvements. there are features that aren't going away anytime soon. Honestly its an excuse I find with most libs. You don't need to rely on svelte too much developing a library. Libs should try and stay as framework agnostic as possible, even split out the part that's framework specific if possible. Reactivity is like async, you only want to use it at entry and exit points, not chained throughout the entire code base. Still, you guys are awesome, I like what you do, I hope svelte won't stop you from continually doing awesome stuff!

**Comment by jycouet** [comment] 2024-08-31 14:24
I'm 100% with you @adminy, I like what they do, a lot. Please continu to do awesome stuff.

I didn't play much with Svelte 5 _(but would like to start on a side project)_.

I have 2 questions/topic: 
1/ Can you remove the warning about Svelte 5 on installing the lib? (I think it's the peerDeps requirement)

2/ Even if stores are not the flagship of Svelte 5, they are still here! So I think that everything should still work as is. Correct? 
@adminy did you try to mix runes & node stores for example? Or you are staying on stores for now?

---

BTW, I'm using xyflow in www.remult.dev for the admin part for userland 😉
Very cool stuff, keep going, we love it
![image](https://github.com/user-attachments/assets/2bc3a7de-7cb6-43eb-ab24-06fca3b4eaf2)

**Comment by moklick** [comment] 2024-09-01 13:48
Hey @adminy I wouldn't say it's an excuse. It's also not true that there were no breaking changes in the last weeks. We need to wait until it's stable to be able to decide about the API for Svelte Flow. We thought that we can use the new `state` rune for nodes and edges but it turned out that it's way too slow. Then we tried `state.frozen` but it was still very slow too. We found a performance issue which was fixed and in the meantime `state.frozen` was renamed to `state.raw`. It wouldn't make sense now to decide on an API if so important things still change.

**Comment by adminy** [comment] 2024-09-01 14:09
> I have 2 questions/topic: 1/ Can you remove the warning about Svelte 5 on installing the lib? (I think it's the peerDeps requirement)

yes, you can for most libs by installing with @next but not this one.

> 2/ Even if stores are not the flagship of Svelte 5, they are still here! So I think that everything should still work as is. Correct? @adminy did you try to mix runes & node stores for example? Or you are staying on stores for now?

I only run with runes mode. used to polyfill stores, but no more.

> BTW, I'm using xyflow in [www.remult.dev](http://www.remult.dev) for the admin part for userland 😉 Very cool stuff, keep going, we love it !

looks awesome! 


@moklick I understand that performance with many nodes wouldn't be great with svelte 5, that's why I was saying it to be treated like a library. Should be updated not on a frame by frame basis, it has to be interfaced as any other library. The node update functions just exposed and then the loop to be user controlled. If you're going to handle that in the library itself, you're just going to have to rewrite bits every time there is a framework update.

**Comment by jycouet** [comment] 2024-09-01 14:55
> used to polyfill stores

Hummm? How? You have a pseudo code somewhere ?

**Comment by adminy** [comment] 2024-09-01 16:17
Well I had mine just inline overwrites in vite config, but there is much better solutions out there. i.e. https://github.com/srav001/katai

**Comment by peterkogo** [comment] 2024-10-24 09:12
I just checked out the new release, and it appears that version [5.0.0-next.264](https://github.com/sveltejs/svelte/releases/tag/svelte%405.0.0-next.264) fixed all performance issues with the current version of Svelte Flow. These were caused by the `immutable` option not working correctly.

As Svelte 5 is designed to be backwards compatible, you can start hacking away on your projects with the newest Svelte version right away.

The release came out of the blue for me, and I still have a couple of things on my plate for the next 2 weeks. Will start to port the library immediately after, for a second time... Hoping the migration scripts are fixed until then :fingers_crossed:

Please note that for us this also means moving towards the 1.0.0 release, so we'll have to work on stabilizing a couple of APIs and improving/rewriting some docs. The most significant change will probably be, that we'll have to make nodes & edges immutable. No more `node.selected = true`. It was nice while it lasted :smiling_face_with_tear:

**Comment by peterkogo** [comment] 2024-10-24 09:16
As the [performance issues are fixed now](https://stackblitz.com/edit/spvqcm-wbkjjk?file=package.json), I will close this issue.

**Closed by peterkogo** 2024-10-24 09:16 UTC
Labels: svelte
