### ISSUE TITLE
Support multiple edges/paths between a pair of nodes

### ISSUE THREAD

**Issue by sinoryx** [xyflow/xyflow#3749] opened 2023-12-28 09:06 UTC
### Please describe the feature that you want to propose

A similar effect I want is the BiDirectional egdes in [this example](https://reactflow.dev/examples/edges/custom-edges).

But in this example it's very complicated to achieve that, as we need to write some customized logic to calculate the path. It would be great to let the library automatically calculate the paths and do the layout if multiple edges exists between a pair of nodes.

Or is there any other best practice for this?

Thanks!

**Comment by myselfrk** [comment] 2023-12-30 15:05
@sinoryx  **multiple edges exists between a pair of nodes** I think will not have more than two connections ?

**Comment by moklick** [comment] 2024-01-03 11:59
duplicate of #3758

**Closed by moklick** 2024-01-03 11:59 UTC
Labels: feature request
