### ISSUE TITLE
Using reactStrictMode  results in the error: "It looks like you've created a new nodeTypes or edgeTypes object"

### ISSUE THREAD

**Issue by alikleit** [xyflow/xyflow#3835] opened 2024-01-26 13:17 UTC
### Describe the Bug

using `reactStrictMode` results in the error:
> It looks like you've created a new nodeTypes or edgeTypes object

![image](https://github.com/xyflow/xyflow/assets/122785904/88222982-74f7-45b1-ace5-b5277a528732)

I'm aware that `reactStrictMode` renders the component twice and for several debugging reasons. Therefore, shouldn't this be properly handled from the `ReactFlow` context?

### Your Example Website or App
[reproduced here](https://github.com/alikleit/react-flow-strict-mode)

### Steps to Reproduce the Bug or Issue

1. npx create-next-app@latest
2. set `reactStrictMode` to `true`
3. paste the example:
```
const initialNodes = [
  { id: '1', position: { x: 0, y: 0 }, data: { label: '1' } },
  { id: '2', position: { x: 0, y: 100 }, data: { label: '2' } },
];
const initialEdges = [{ id: 'e1-2', source: '1', target: '2' }];

export default function Home() {
  return (

    <div style={{ width: '100vw', height: '100vh' }}>
      <ReactFlow nodes={initialNodes} edges={initialEdges} />
    </div>
  );
}
```

4. run the app

### Expected behavior

No Warnings to Appear when using `reactStrictMode`

### Platform

- OS: Window
- Browser: Edge
- Version: 120.0.2210.144

**Comment by hayleigh-dot-dev** [comment] 2024-01-30 15:05
Hi there @alikleit! This has been fixed in our v12 beta (confirmed by taking your reproduction and swapping out `reactflow` for `@xyflow/react`): the issue I think stems from a fairly naive approach we were taking to tracking this particular warning. I think there's some interplay with next as well, because we can't reproduce the error in other examples even with `<React.StrictMode />`.

You can safely (although annoyingly) ignore this while you're on v11 and using next :)

**Closed by hayleigh-dot-dev** 2024-01-30 15:05 UTC
